# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Ran AYouri
tagline:          ''
# description:     'Institut fur Mathematik, Universität Zürich'
description:      ''
url:              https://www.ranazouri.com
baseurl:          /

author:
  name:           'Ran Ayouri'
  url:            https://www.ranazouri.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ransass/ransass.github.io
